language: java
jdk:
  - oraclejdk8
script: mvn test --fail-at-end --batch-mode -Dmatsim.preferLocalDtds=true
#-Dmaven.test.redirectTestOutputToFile

cache:
  directories:
  - $HOME/.m2

env:
  global:
    - export MAVEN_OPTS="-Xmx2500m"


